# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyHuwRm_KKCTom-NYZPyCTtfkaml5QyE
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import networkx as nx

# Load datasets
iris = sns.load_dataset('iris')

# Load Adult dataset from UCI (or local CSV)
adult = pd.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',
    header=None,
    names=['age','workclass','fnlwgt','education','education-num','marital-status',
           'occupation','relationship','race','sex','capital-gain','capital-loss',
           'hours-per-week','native-country','income']
)

plt.figure(figsize=(7,5))
sns.histplot(iris['sepal_length'], bins=20, kde=True, color='skyblue')
plt.title("1D: Distribution of Sepal Length (Iris)")
plt.xlabel("Sepal Length (cm)")
plt.show()

sns.scatterplot(x='sepal_length', y='petal_length', hue='species', data=iris)
plt.title("2D: Sepal vs Petal Length (Iris)")
plt.show()

import plotly.express as px

fig=px.scatter_3d(
    x=iris['sepal_length'],
    y=iris['petal_width'],
    z=iris['sepal_width'],
    color=iris['species'],
    size=iris['petal_length']
)

fig

import networkx as nx

fig1=px.treemap(adult,path=['workclass', 'occupation', 'income'])

fig1

sns.pairplot(iris, hue='species')
plt.suptitle("Multidimensional Visualization: Pair Plot (Iris)", y=1.02)
plt.show()

import networkx as nx
edge = adult[['education', 'occupation']].dropna().drop_duplicates()
G=nx.from_pandas_edgelist(edge,'education', 'occupation')
pos=nx.spring_layout(G,k=10,)
# spring_layout is a graph layout algorithm in NetworkX that determines the positions (x, y coordinates) of nodes in a graph before drawing it.
nx.draw(G,pos,with_labels=True,node_size=700,font_size=9)

